(function(g){var window=this;'use strict';var Hjb=function(a,b){a.ib("onAutonavCoundownStarted",b)},j5=function(a,b,c){g.kp(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.gh(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.GP&&(b.lengthText?(e=b.lengthText||null,f=b.Rx||null):b.lengthSeconds&&(e=g.zy(b.lengthSeconds),f=g.zy(b.lengthSeconds,!0)));var h=!!d;d=h&&g.EP(d).type==="RD";var l=b instanceof g.GP?b.isLivePlayback:null,m=b instanceof g.GP?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],t=[];n&&r.push(n);p&&(r.push(p),t.push(p));q&&t.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.nD("Ver $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Jl(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:t.join(" \u2022 "),autoplayAlternativeHeader:b.Ft};b instanceof g.FP&&(c.playlist_length=b.playlistLength);a.update(c)},k5=function(a){var b=a.U(),c=b.D;
g.T.call(this,{I:"a",S:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",La:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],va:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],va:"En vivo"},
{I:"div",La:["ytp-autonav-upcoming-stamp"],va:"Pr\u00f3ximamente"},{I:"div",S:"ytp-autonav-list-overlay",V:[{I:"div",S:"ytp-autonav-mix-text",va:"Mix"},{I:"div",S:"ytp-autonav-mix-icon"}]}]},{I:"div",La:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],va:"{{title}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],va:"{{author}}"},{I:"div",La:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],va:"{{views_and_publish_time}}"}]});this.J=
a;this.suggestion=null;this.j=c;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},l5=function(a,b){b=b===void 0?!1:b;
g.T.call(this,{I:"div",S:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.cancelCommand=this.G=void 0;this.C=0;this.container=new g.T({I:"div",S:"ytp-autonav-endscreen-countdown-container"});g.P(this,this.container);this.container.Ia(this.element);b=a.U();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.T(a,"videodatachange",this.onVideoDataChange);this.j=new g.T({I:"div",S:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-header"},{I:"div",S:"ytp-autonav-endscreen-upnext-alternative-header",va:"{{autoplayAlternativeHeader}}"},{I:"a",S:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},V:[{I:"div",S:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},V:[{I:"div",X:{"aria-label":"{{timestamp}}"},La:["ytp-autonav-timestamp"],
va:"{{duration}}"},{I:"div",La:["ytp-autonav-live-stamp"],va:"En vivo"},{I:"div",La:["ytp-autonav-upcoming-stamp"],va:"Pr\u00f3ximamente"}]},{I:"div",S:"ytp-autonav-endscreen-video-info",V:[{I:"div",S:"ytp-autonav-endscreen-premium-badge"},{I:"div",S:"ytp-autonav-endscreen-upnext-title",va:"{{title}}"},{I:"div",S:"ytp-autonav-endscreen-upnext-author",va:"{{author}}"},{I:"div",S:"ytp-autonav-view-and-date",va:"{{views_and_publish_time}}"},{I:"div",S:"ytp-autonav-author-and-view",va:"{{author_and_views}}"}]}]}]});
g.P(this,this.j);this.j.Ia(this.container.element);d||this.T(this.j.Ea("ytp-autonav-endscreen-link-container"),"click",this.jV);this.J.createClientVe(this.container.element,this,115127);this.J.createClientVe(this.j.Ea("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.T({I:"div",S:"ytp-autonav-overlay"});g.P(this,this.overlay);this.overlay.Ia(this.container.element);this.B=new g.T({I:"div",S:"ytp-autonav-endscreen-button-container"});g.P(this,this.B);this.B.Ia(this.container.element);
this.cancelButton=new g.T({I:"button",La:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},va:"Cancelar"});g.P(this,this.cancelButton);this.cancelButton.Ia(this.B.element);this.cancelButton.listen("click",this.f5,this);this.J.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.T({I:"a",La:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",b.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"Reproducir siguiente video"},va:"Reproducir ahora"});g.P(this,this.playButton);this.playButton.Ia(this.B.element);this.playButton.listen("click",this.jV,this);this.J.L("web_player_autonav_next_button_renderer")?(this.J.createServerVe(this.playButton.element,this.playButton,!0),(b=this.J.getVideoData())&&Ijb(this,b)):this.J.createClientVe(this.playButton.element,
this,115130);this.D=new g.Zo(function(){Jjb(c)},500);
g.P(this,this.D);this.iV();this.T(a,"autonavvisibility",this.iV);this.J.L("web_autonav_color_transition")&&(this.T(a,"autonavchange",this.e5),this.T(a,"onAutonavCoundownStarted",this.Kaa))},m5=function(a){var b=a.J.xo(!0,a.J.isFullscreen());
g.kp(a.container.element,"ytp-autonav-endscreen-small-mode",a.Og(b));g.kp(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.RM);g.kp(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Hf());g.kp(a.J.getRootNode(),"countdown-running",a.Ol());g.kp(a.container.element,"ytp-player-content",a.J.Hf());g.fm(a.overlay.element,{width:b.width+"px"});if(!a.Ol()){a.J.Hf()?Kjb(a,Math.round(Ljb(a)/1E3)):Kjb(a);b=!!a.suggestion&&!!a.suggestion.Ft;var c=a.J.Hf()||!b;
g.kp(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.kp(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.nx(a.B,a.J.Hf());g.kp(a.element,"ytp-enable-w2w-color-transitions",Mjb(a))}},Jjb=function(a){var b=Ljb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);Kjb(a,Math.ceil((b-c)/1E3));b-c<=500&&a.Ol()?a.select(!0):a.Ol()&&a.D.start()},Ljb=function(a){if(a.J.isFullscreen()){var b;
a=(b=a.J.getVideoData())==null?void 0:b.KD;return a===-1||a===void 0?8E3:a}return a.J.Ut()>=0?a.J.Ut():g.kC(a.J.U().experiments,"autoplay_time")||1E4},Ijb=function(a,b){a.J.L("web_player_autonav_next_button_renderer");
b=b.G4;a.G=b==null?void 0:b.navigationEndpoint;b=b==null?void 0:b.trackingParams;a.playButton&&b&&a.J.setTrackingParams(a.playButton.element,b)},Mjb=function(a){var b;
return!((b=a.J.getVideoData())==null||!b.watchToWatchTransitionRenderer)},Kjb=function(a,b){b=b===void 0?-1:b;
a=a.j.Ea("ytp-autonav-endscreen-upnext-header");g.pe(a);if(b>=0){b=String(b);var c="A continuaci\u00f3n, en $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="A continuaci\u00f3n, en $SECONDS".indexOf(c);if(d>=0){a.appendChild(g.ne("A continuaci\u00f3n, en $SECONDS".slice(0,d)));var e=g.me("span");g.ep(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.te(e,b);a.appendChild(e);a.appendChild(g.ne("A continuaci\u00f3n, en $SECONDS".slice(d+c.length)));return}}g.te(a,"A continuaci\u00f3n")},n5=
function(a,b){g.T.call(this,{I:"div",
La:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},o5=function(a){g.T.call(this,{I:"div",
La:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},V:[{I:"div",S:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-upnext-top",V:[{I:"span",S:"ytp-upnext-header",va:"A continuaci\u00f3n"},{I:"span",S:"ytp-upnext-title",va:"{{title}}"},{I:"span",S:"ytp-upnext-author",va:"{{author}}"}]},{I:"a",S:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"Reproducir siguiente video"},V:[{I:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},V:[{I:"circle",S:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",S:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",S:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",S:"ytp-upnext-bottom",V:[{I:"span",S:"ytp-upnext-cancel"},{I:"span",S:"ytp-upnext-paused",
va:"La reproducci\u00f3n autom\u00e1tica est\u00e1 en pausa"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ea("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.Zo(this.vJ,5E3,this);this.B=0;var b=this.Ea("ytp-upnext-cancel");this.cancelButton=new g.T({I:"button",La:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"Cancelar reproducci\u00f3n autom\u00e1tica"},va:"Cancelar"});g.P(this,this.cancelButton);this.cancelButton.listen("click",
this.g5,this);this.cancelButton.Ia(b);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.P(this,this.D);this.api.createClientVe(this.element,this,18788);b=this.Ea("ytp-upnext-autoplay-icon");this.T(b,"click",this.i5);this.api.createClientVe(b,this,115130);this.kV();this.T(a,"autonavvisibility",this.kV);this.T(a,"mdxnowautoplaying",this.zba);this.T(a,"mdxautoplaycanceled",this.Aba);g.kp(this.element,"ytp-upnext-mobile",this.api.U().B)},Njb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=(c=a.api.getVideoData())==null?void 0:c.KD;return a===-1||a===void 0?8E3:a}return a.api.Ut()>=0?a.api.Ut():g.kC(a.api.U().experiments,"autoplay_time")||1E4},Ojb=function(a,b){b=Njb(a,b);
var c=Math,d=c.min;var e=(0,g.S)()-a.B;c=d.call(c,e,b);b=b===0?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));b>=1&&a.Ol()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Ol()&&a.j.start()},p5=function(a){n5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.T({I:"div",S:"ytp-suggestion-panel",V:[{I:"div",La:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],va:"M\u00e1s videos"}]});this.N=new g.T({I:"div",S:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new l5(this.player);g.P(this,this.B);this.B.Ia(this.element);a.getVideoData().Vf?this.j=this.B:(this.j=new o5(a),g.JR(this.player,this.j.element,4),g.P(this,this.j));this.overlay=new g.T({I:"div",
S:"ytp-autonav-overlay-cancelled-state"});g.P(this,this.overlay);this.overlay.Ia(this.element);this.D=new g.BE(this);g.P(this,this.D);g.P(this,this.table);this.table.Ia(this.element);this.table.show();g.P(this,this.N);this.N.Ia(this.table.element);this.hide()},q5=function(a){var b=a.Hf();
b!==a.G&&(a.G=b,a.player.publish("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},r5=function(a,b){g.T.call(this,{I:"button",
La:["ytp-watch-on-youtube-button","ytp-button"],va:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.K2();this.buttonType===2&&g.gp(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.K2);g.nx(this,!0)},s5=function(a,b){n5.call(this,a,"embeds-lite-endscreen");
this.J=a;this.Le=b;this.J.createClientVe(this.element,this,156943);this.watchButton=new r5(a,2);g.P(this,this.watchButton);this.watchButton.Ia(this.element);this.hide()},Pjb=function(a){n5.call(this,a,"subscribecard-endscreen");
this.j=new g.T({I:"div",S:"ytp-subscribe-card",V:[{I:"img",S:"ytp-author-image",X:{src:"{{profilePicture}}"}},{I:"div",S:"ytp-subscribe-card-right",V:[{I:"div",S:"ytp-author-name",va:"{{author}}"},{I:"div",S:"html5-subscribe-button-container"}]}]});g.P(this,this.j);this.j.Ia(this.element);var b=a.getVideoData();this.subscribeButton=new g.yY("Suscribirse",null,"Anular suscripci\u00f3n",null,!0,!1,b.im,b.subscribed,"trailer-endscreen",null,a,!1);g.P(this,this.subscribeButton);this.subscribeButton.Ia(this.j.Ea("html5-subscribe-button-container"));
this.T(a,"videodatachange",this.Sa);this.Sa();this.hide()},t5=function(a){var b=a.U(),c=g.xE||g.IO?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.T.call(this,{I:"a",La:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{I:"div",S:"ytp-videowall-still-image",X:{style:"{{background}}"}},{I:"span",S:"ytp-videowall-still-info",X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-info-bg",V:[{I:"span",S:"ytp-videowall-still-info-content",X:c,V:[{I:"span",S:"ytp-videowall-still-info-title",va:"{{title}}"},
{I:"span",S:"ytp-videowall-still-info-author",va:"{{author_and_views}}"},{I:"span",S:"ytp-videowall-still-info-live",va:"En vivo"},{I:"span",S:"ytp-videowall-still-info-duration",va:"{{duration}}"}]}]}]},{I:"span",La:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",S:"ytp-videowall-still-listlabel-length",V:[" (",{I:"span",va:"{{playlist_length}}"},")"]}]},{I:"span",La:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},V:[{I:"span",S:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",S:"ytp-videowall-still-listlabel-length",va:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.BE(this);g.P(this,this.j);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.j.T(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,this);this.onVideoDataChange()},u5=function(a){n5.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.N=!1;this.Y=null;this.B=new g.BE(this);g.P(this,this.B);this.K=new g.Zo(function(){g.gp(b.element,"ytp-show-tiles")},0);
g.P(this,this.K);var c=new g.T({I:"button",La:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"Anterior"},V:[g.ux()]});g.P(this,c);c.Ia(this.element);c.listen("click",this.m5,this);this.table=new g.kx({I:"div",S:"ytp-endscreen-content"});g.P(this,this.table);this.table.Ia(this.element);c=new g.T({I:"button",La:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"Siguiente"},V:[g.vx()]});g.P(this,c);c.Ia(this.element);c.listen("click",this.l5,this);a.getVideoData().Vf?this.j=new l5(a,!0):this.j=
new o5(a);g.P(this,this.j);g.JR(this.player,this.j.element,4);a.createClientVe(this.element,this,158789);this.hide()},v5=function(a){return g.KR(a.player)&&a.yE()&&!a.D},w5=function(a){var b=a.Hf();
b!==a.N&&(a.N=b,a.player.publish("autonavvisibility"))},x5=function(a){n5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new r5(a,1);g.P(this,this.watchButton);this.watchButton.Ia(this.element);g.v9a(a)&&(this.j=new g.b1(a),g.P(this,this.j),this.B=new g.T({I:"div",La:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},V:[this.j]}),g.P(this,this.B),this.j.Ia(this.B.element),this.B.Ia(this.element));a.createClientVe(this.element,this,156914);this.hide()},Tjb=function(a){g.SX.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.BE(this);g.P(this,this.listeners);var c=a.U(),d=a.getVideoData();d=d&&d.limitedPlaybackDurationInSeconds!==0;g.js(g.TO(c))&&d&&!g.FR(a)?(this.B=!0,this.endScreen=new s5(a,g.qR(a))):a.fd()?this.endScreen=new x5(a):Qjb(a)?(this.D=!0,Rjb(this),this.j?this.endScreen=new p5(a):this.endScreen=new u5(a)):c.Hg?this.endScreen=new Pjb(a):this.endScreen=new n5(a);g.P(this,this.endScreen);g.JR(a,this.endScreen.element,4);Sjb(this);
this.listeners.T(a,"videodatachange",this.onVideoDataChange,this);this.listeners.T(a,g.cD("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.T(a,g.dD("endscreen"),function(e){b.onCueRangeExit(e)})},Rjb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.mm&&a.C===b.Vf)return!1;a.j=b.mm;a.C=b.Vf;return!0},Qjb=function(a){a=a.U();
return a.Bd&&!a.Hg},Sjb=function(a){a.player.qf("endscreen");
var b=a.player.getVideoData();b=new g.aD(Math.max((b.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.aD(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.jf([b,c])};
g.BR.prototype.Ut=g.da(14,function(){return this.app.Ut()});
g.E_.prototype.Ut=g.da(13,function(){return this.getVideoData().i_});
g.xR.prototype.Ps=g.da(12,function(a){this.Li().Ps(a)});
g.NY.prototype.Ps=g.da(11,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.TZ.prototype.Ps=g.da(10,function(a){this.overflowButton&&this.overflowButton.Ps(a)});
g.xR.prototype.Qs=g.da(9,function(a){this.Li().Qs(a)});
g.SY.prototype.Qs=g.da(8,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.TZ.prototype.Qs=g.da(7,function(a){this.shareButton&&this.shareButton.Qs(a)});
g.xR.prototype.xC=g.da(6,function(a){this.Li().xC(a)});
g.rY.prototype.xC=g.da(5,function(a){this.QS!==a&&(this.QS=a,this.ir())});
g.xR.prototype.wC=g.da(4,function(a){this.Li().wC(a)});
g.TZ.prototype.wC=g.da(3,function(a){this.PS!==a&&(this.PS=a,this.gr())});g.z(k5,g.T);k5.prototype.select=function(){this.J.xp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.cF||void 0)&&this.J.logClick(this.element)};
k5.prototype.onClick=function(a){g.DS(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
k5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.z(l5,g.T);g.k=l5.prototype;g.k.CI=function(a){this.suggestion!==a&&(this.suggestion=a,j5(this.j,a),this.playButton.updateValue("url",this.suggestion.Jl()),m5(this))};
g.k.Ol=function(){return this.C>0};
g.k.GC=function(){this.Ol()||(this.C=Date.now(),Jjb(this),Hjb(this.J,Ljb(this)),g.kp(this.J.getRootNode(),"countdown-running",this.Ol()))};
g.k.Cy=function(){this.Vq();Jjb(this);var a=this.j.Ea("ytp-autonav-endscreen-upnext-header");a&&g.te(a,"A continuaci\u00f3n")};
g.k.Vq=function(){this.Ol()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,a===void 0?!1:a);this.Vq()};
g.k.jV=function(a){g.DS(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.logClick(this.playButton.element):a.currentTarget===this.j.Ea("ytp-autonav-endscreen-link-container")&&(a=this.j.Ea("ytp-autonav-endscreen-link-container"),this.J.logVisibility(a,!0),this.J.logClick(a)),this.J.L("web_player_autonav_next_button_renderer")&&this.G?(this.J.ib("innertubeCommand",this.G),this.Vq()):this.select())};
g.k.f5=function(){this.J.logClick(this.cancelButton.element);g.DR(this.J,!0);this.cancelCommand&&this.J.ib("innertubeCommand",this.cancelCommand)};
g.k.onVideoDataChange=function(a,b){this.J.L("web_player_autonav_next_button_renderer")&&Ijb(this,b);var c;this.cancelCommand=(c=b.C4)==null?void 0:c.command};
g.k.Kaa=function(a){if(Mjb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=b==null?void 0:b.fromColorPaletteDark;b=b==null?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.Ky(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.Ky(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.Ky(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.Ky(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.Ky(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.Ky(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.kp(this.element,"ytp-w2w-animate",!0)}};
g.k.e5=function(a){this.J.L("web_autonav_color_transition")&&a!==2&&g.kp(this.element,"ytp-w2w-animate",!1)};
g.k.iV=function(){var a=this.J.Hf();this.K&&this.Fb!==a&&g.nx(this,a);m5(this);this.J.logVisibility(this.container.element,a);this.J.logVisibility(this.cancelButton.element,a);this.J.logVisibility(this.j.Ea("ytp-autonav-endscreen-link-container"),a);this.J.logVisibility(this.playButton.element,a)};
g.k.Og=function(a){return a.width<400||a.height<459};g.z(n5,g.T);g.k=n5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.yE=function(){return!1};
g.k.Hf=function(){return!1};
g.k.f_=function(){return!1};g.z(o5,g.T);g.k=o5.prototype;g.k.vJ=function(){this.notification&&(this.D.stop(),this.Lc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.CI=function(a){this.suggestion=a;j5(this,a,"hqdefault.jpg")};
g.k.kV=function(){g.nx(this,this.api.Hf());this.api.logVisibility(this.element,this.api.Hf());this.api.logVisibility(this.Ea("ytp-upnext-autoplay-icon"),this.api.Hf());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.Hf())};
g.k.Iba=function(){window.focus();this.vJ()};
g.k.GC=function(a){var b=this;this.Ol()||(g.kv("a11y-announce","A continuaci\u00f3n "+this.suggestion.title),this.B=(0,g.S)(),this.j=new g.Zo(function(){Ojb(b,a)},25),Ojb(this,a),Hjb(this.api,Njb(this,a)));
g.ip(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.T.prototype.hide.call(this)};
g.k.Ol=function(){return!!this.j};
g.k.Cy=function(){this.Vq();this.B=(0,g.S)();Ojb(this);g.gp(this.element,"ytp-upnext-autoplay-paused")};
g.k.Vq=function(){this.Ol()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=a===void 0?!1:a;if(this.api.U().L("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var b=Notification.permission;b==="default"?Notification.requestPermission():b!=="granted"||document.hasFocus()||(this.vJ(),this.notification=new Notification("A continuaci\u00f3n",{body:this.suggestion.title,icon:this.suggestion.gh()}),this.C=this.T(this.notification,"click",this.Iba),this.D.start())}this.Vq();this.api.nextVideo(!1,a)};
g.k.i5=function(a){!g.se(this.cancelButton.element,a.target)&&g.DS(a,this.api)&&(this.api.Hf()&&this.api.logClick(this.Ea("ytp-upnext-autoplay-icon")),this.select())};
g.k.g5=function(){this.api.Hf()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.DR(this.api,!0)};
g.k.zba=function(a){this.api.getPresentingPlayerType();this.show();this.GC(a)};
g.k.Aba=function(){this.api.getPresentingPlayerType();this.Vq();this.hide()};
g.k.xa=function(){this.Vq();this.vJ();g.T.prototype.xa.call(this)};g.z(p5,n5);g.k=p5.prototype;g.k.create=function(){n5.prototype.create.call(this);this.D.T(this.player,"appresize",this.tD);this.D.T(this.player,"onVideoAreaChange",this.tD);this.D.T(this.player,"videodatachange",this.onVideoDataChange);this.D.T(this.player,"autonavchange",this.lV);this.D.T(this.player,"onAutonavCancelled",this.j5);this.onVideoDataChange()};
g.k.show=function(){n5.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.DR(this.player,!1);g.KR(this.player)&&this.yE()&&!this.C?(q5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.GC():this.videoData.autonavState===3&&this.j.Cy()):(g.DR(this.player,!0),q5(this));this.tD()};
g.k.hide=function(){n5.prototype.hide.call(this);this.j.Cy();q5(this)};
g.k.tD=function(){var a=this.player.xo(!0,this.player.isFullscreen());q5(this);m5(this.B);g.kp(this.element,"ytp-autonav-cancelled-small-mode",this.Og(a));g.kp(this.element,"ytp-autonav-cancelled-tiny-mode",this.VK(a));g.kp(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.fm(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.kp(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.L("web_player_autonav_empty_suggestions_fix")){var b=g.qQ(this.videoData);b&&(this.j.CI(b),this.j!==this.B&&this.B.CI(b))}if(a&&a.length)for(b=0;b<Ujb.length;++b){var c=Ujb[b];if(a&&a[c]){this.videos[b]=new k5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,j5(d,c));g.P(this,this.videos[b]);this.videos[b].Ia(this.N.element)}}this.tD()}};
g.k.lV=function(a){a===1?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Vq(),this.Fb&&this.tD()):(this.K=!0,this.Hf()&&(a===2?this.j.GC():a===3&&this.j.Cy()))};
g.k.j5=function(a){a?this.lV(1):(this.C=null,this.K=!1)};
g.k.yE=function(){return this.videoData.autonavState!==1};
g.k.Og=function(a){return(a.width<910||a.height<459)&&!this.VK(a)&&!(a.width<=400||a.height<=360)};
g.k.VK=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.k.Hf=function(){return this.Fb&&g.KR(this.player)&&this.yE()&&!this.C};
var Ujb=[1,3,2,4];g.z(r5,g.T);g.k=r5.prototype;g.k.K2=function(){switch(this.buttonType){case 1:var a="Mirar de nuevo en YouTube";var b=156915;break;case 2:a="Seguir mirando en YouTube";b=156942;break;default:a="Seguir mirando en YouTube",b=156942}this.update({content:a});this.J.hasVe(this.element)&&this.J.destroyVe(this.element);this.J.createClientVe(this.element,this,b)};
g.k.onClick=function(a){this.J.L("web_player_log_click_before_generating_ve_conversion_params")&&this.J.logClick(this.element);g.ES(this.getVideoUrl(),this.J,a);this.J.L("web_player_log_click_before_generating_ve_conversion_params")||this.J.logClick(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.U();if(g.KO(b)){var c={};g.KO(b)&&g.lR(this.J,"addEmbedsConversionTrackingParams",[c]);a=g.Ri(a,c)}return a};
g.k.logVisibility=function(){this.J.logVisibility(this.element,this.Fb&&this.Z)};
g.k.show=function(){g.T.prototype.show.call(this);this.logVisibility()};
g.k.hide=function(){g.T.prototype.hide.call(this);this.logVisibility()};
g.k.Kc=function(a){g.T.prototype.Kc.call(this,a);this.logVisibility()};g.z(s5,n5);s5.prototype.show=function(){this.player.getPlayerState()!==3&&(n5.prototype.show.call(this),this.Le.wC(!0),this.Le.Qs(!0),this.J.U().Ve||this.Le.Ps(!0),this.J.logVisibility(this.element,!0),this.watchButton.Kc(!0))};
s5.prototype.hide=function(){n5.prototype.hide.call(this);this.Le.wC(!1);this.Le.Qs(!1);this.Le.Ps(!1);this.J.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(Pjb,n5);Pjb.prototype.Sa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.im;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.z(t5,g.T);t5.prototype.select=function(){this.api.xp(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.cF||void 0)&&this.api.logClick(this.element)};
t5.prototype.onClick=function(a){if(g.KO(this.api.U())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var b=this.suggestion.Jl(),c={};g.GR(this.api,c);b=g.Ri(b,c);g.ES(b,this.api,a)}else g.DS(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
t5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
t5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.U();this.B=a.Jf?!1:b.D};g.z(u5,n5);g.k=u5.prototype;g.k.create=function(){n5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.vr();this.B.T(this.player,"appresize",this.vr);this.B.T(this.player,"onVideoAreaChange",this.vr);this.B.T(this.player,"videodatachange",this.onVideoDataChange);this.B.T(this.player,"autonavchange",this.zN);this.B.T(this.player,"onAutonavCancelled",this.k5);a=this.videoData.autonavState;a!==this.Y&&this.zN(a);this.B.T(this.element,"transitionend",this.Wca)};
g.k.destroy=function(){g.Ds(this.B);g.qb(this.stills);this.stills=[];n5.prototype.destroy.call(this);g.ip(this.element,"ytp-show-tiles");this.K.stop();this.Y=this.videoData.autonavState};
g.k.yE=function(){return this.videoData.autonavState!==1};
g.k.show=function(){var a=this.Fb;n5.prototype.show.call(this);g.ip(this.element,"ytp-show-tiles");this.player.U().B?g.ap(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.DR(this.player,!1);v5(this)?(w5(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.j.select(!0):this.j.GC():this.videoData.autonavState===3&&this.j.Cy()):(g.DR(this.player,!0),w5(this));a!==this.Fb&&this.player.logVisibility(this.element,!0)};
g.k.hide=function(){var a=this.Fb;n5.prototype.hide.call(this);this.j.Cy();w5(this);a!==this.Fb&&this.player.logVisibility(this.element,!1)};
g.k.Wca=function(a){a.target===this.element&&this.vr()};
g.k.vr=function(){var a,b,c,d;var e=((a=this.videoData)==null?0:(b=a.suggestions)==null?0:b.length)?(c=this.videoData)==null?void 0:c.suggestions:[(d=this.videoData)==null?void 0:g.qQ(d)];if(e.length){g.gp(this.element,"ytp-endscreen-paginate");var f=this.J.xo(!0,this.J.isFullscreen());if(a=g.qR(this.J))a=a.Mh()?48:32,f.width-=a*2;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;p>0&&(a<l||b<m);){var q=a/2,r=b/2,t=a<=l-2&&p>=r*n,u=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&u)p-=q*n,b+=2;else if(t)p-=r*n,a+=2;else if(u)p-=q*n,b+=2;else break}d=!1;p>=3*n&&c*n-p<=6&&(b>=4||a>=4)&&(d=!0);n=a*96;p=b*54;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.wm(f,n,p);g.fm(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.CI(g.qQ(this.videoData));this.j instanceof
l5&&m5(this.j);g.kp(this.element,"ytp-endscreen-takeover",v5(this));w5(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,t=0,d&&l>=a-2&&m>=b-2?t=1:m%2===0&&l%2===0&&(m<2&&l<2?m===0&&l===0&&(t=2):t=2),q=g.Hd(q+this.C,c),t!==0){r=this.stills[h];r||(r=new t5(this.player),this.stills[h]=r,f.appendChild(r.element));u=Math.floor(p*m/b);var y=Math.floor(n*l/a),B=Math.floor(p*(m+t)/b)-u-4,C=Math.floor(n*(l+t)/a)-y-4;g.sm(r.element,y,u);g.wm(r.element,C,B);g.fm(r.element,"transitionDelay",
(m+l)/20+"s");g.kp(r.element,"ytp-videowall-still-mini",t===1);g.kp(r.element,"ytp-videowall-still-large",t>2);t=Math.max(C,B);g.kp(r.element,"ytp-videowall-still-round-large",t>=256);g.kp(r.element,"ytp-videowall-still-round-medium",t>96&&t<256);g.kp(r.element,"ytp-videowall-still-round-small",t<=96);q=e[q];r.suggestion!==q&&(r.suggestion=q,t=r.api.U(),u=g.fp(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",j5(r,q,u),g.KO(t)&&!r.api.L("web_player_log_click_before_generating_ve_conversion_params")&&
(t=q.Jl(),u={},g.lR(r.api,"addEmbedsConversionTrackingParams",[u]),t=g.Ri(t,u),r.updateValue("url",t)),(q=(q=q.sessionData)&&q.itct)&&r.api.setTrackingParams(r.element,q));h++}f.ariaBusy="false";g.kp(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.re(a.element),g.pb(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.qQ(a)?(this.C=0,this.videoData=a,this.vr()):this.player.ma("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.k.l5=function(){this.C+=this.stills.length;this.vr()};
g.k.m5=function(){this.C-=this.stills.length;this.vr()};
g.k.f_=function(){return this.j.Ol()};
g.k.zN=function(a){a===1?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Vq(),this.Fb&&this.vr()):(this.G=!0,this.Fb&&v5(this)&&(a===2?this.j.GC():a===3&&this.j.Cy()))};
g.k.k5=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.logVisibility(this.stills[a].element,!0);this.zN(1)}else this.D=null,this.G=!1;this.vr()};
g.k.Hf=function(){return this.Fb&&v5(this)};g.z(x5,n5);x5.prototype.show=function(){if(this.player.getPlayerState()!==3){n5.prototype.show.call(this);var a=this.B;if(a){var b=this.j.suggestionData.length>0;g.kp(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;(c=g.qR(this.player))==null||c.xC(!0);this.player.logVisibility(this.element,!0);this.watchButton.Kc(!0)}};
x5.prototype.hide=function(){n5.prototype.hide.call(this);var a;(a=g.qR(this.player))==null||a.xC(!1);this.player.logVisibility(this.element,!1);this.watchButton.Kc(!1)};g.z(Tjb,g.SX);g.k=Tjb.prototype;g.k.zv=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((this.player.fd()||this.B)&&!b)return!0;var c;var d=!!((a==null?0:g.qQ(a))||(a==null?0:(c=a.suggestions)==null?0:c.length));d=!Qjb(this.player)||d;a=a.Pj;c=this.player.pF();return d&&!a&&!c&&!b};
g.k.Hf=function(){return this.endScreen.Hf()};
g.k.y$=function(){return this.Hf()?this.endScreen.f_():!1};
g.k.xa=function(){this.player.qf("endscreen");g.SX.prototype.xa.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Ab().Ee.get("heartbeat"),d=g.qQ(a);!d||b.videoId!==d.videoId||a.IW?(this.player.xp(b.videoId,void 0,void 0,!0,!0,b),c&&c.dL("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.SX.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.SX.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.zv()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.k.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Sjb(this);this.D&&Rjb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new p5(this.player):this.endScreen=new u5(this.player),g.P(this,this.endScreen),g.JR(this.player,this.endScreen.element,4))};g.RX("endscreen",Tjb);})(_yt_player);
